- name: update sources list
  apt: update_cache=yes

- name: install logstash
  apt: name=logstash state=present

- name: move logstash config file
  template: src=templates/logging.conf.j2 dest={{ logstash_conf }}/conf.d/logging.conf

- name: copy the certificate to connect with elasticsearch
  copy: src=templates/{{ client_cert }} dest={{ logstash_conf }}/{{ client_cert }}

- name: start logstash
  systemd: state=started name=logstash
