
---
- name: setting up logstash
  hosts: all
  become: yes
  vars:
    node_name: "data-1"
  roles: 
    - elastic-repo
    - elasticsearch
    - logstash
    - metricbeat
  tags: logstash

- name: setting up kibana
  hosts: all
  become: yes
  vars:
    node_name: "data-2"
  roles: 
    - elastic-repo
    - elasticsearch
    - kibana
    - metricbeat
  tags: kibana

- name: setting up es-master
  hosts: all
  become: yes
  vars:
    node_name: "master"
  roles: 
    - elastic-repo
    - elasticsearch
    - metricbeat
  tags: es-master
